version: "3.9"

services:

  db:
    image: postgres:16
    container_name: tidalbrix-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M


  backend:
    image: ghcr.io/deva-ansh-af/tidalbrix-backend:latest
    container_name: tidalbrix-backend
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_MODE: dummy

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M


  frontend:
    image: ghcr.io/deva-ansh-af/tidalbrix-frontend:latest
    container_name: tidalbrix-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M


  worker:
    image: ghcr.io/deva-ansh-af/tidalbrix-worker:latest
    container_name: tidalbrix-worker
    restart: "no"

    depends_on:
      - backend
      - db

    environment:
      STEP_DELAY_SECONDS: "3"
      APP_MODE: dummy

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M


volumes:
  postgres_data:
